export FLASK_APP='api.py' # Don't change this
export FLASK_ENV='development' # Change it to 'testing' if you want to migrate a test database
export AUTH0_DOMAIN="dev-hsd210wqnr1cmu4f.us.auth0.com" # Enter your AUTH0_DOMAIN
export API_AUDIENCE='coffee' #Enter your API Audience
export DB_URL="postgresql://postgres:123@localhost:5432/agency" #Change username & password
export DB_TEST_URL="postgresql://postgres:123@localhost:5432/casting_test" #Change username & password
export REACT_APP_AUTH0_DOMAIN=dev-hsd210wqnr1cmu4f.us.auth0.com
export REACT_APP_AUTH0_CLIENT_ID=XB9N8QSz5Js70hHK9aDLVelEb0pCTGbT
export REACT_APP_AUTH0_AUDIENCE=coffee
